[tool.poetry]
name = "semantic-shapes"
version = "0.1.0"
description = "Semantic shapes for deep neural networks."
authors = ["Oelin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
